import { AIConfig } from '../AIConfig';

export type AIWeights = {
    SCORE_BASE_VALUE: number;
    SCORE_WIN_CONDITION: number;
    SCORE_TOWN: number;
    SCORE_ENEMY_LAND: number;
    SCORE_DISCONNECT_ENEMY: number;
    SCORE_DEFEND_BASE: number;
    SCORE_HILL: number;
    SCORE_BRIDGE: number;
    SCORE_EXPANSION: number;
    SCORE_AURA_MULTIPLIER: number;
    COST_PENALTY_MULTIPLIER: number;
    SCORE_LOOKAHEAD_TOWN: number;
    SCORE_LOOKAHEAD_BASE: number;
    STRATEGY_EARLY_TURN_LIMIT: number;
    STRATEGY_EARLY_EXPANSION_BONUS: number;
    STRATEGY_EARLY_FARM_BONUS: number;
    STRATEGY_BASE_UPGRADE_BONUS: number;
    STRATEGY_WALL_PRIORITY_BONUS: number;
    STRATEGY_ENDGAME_TURN: number;
    STRATEGY_ENDGAME_ATTACK_BONUS: number;
    SAVE_FOR_TARGET_MAX_TURNS: number;
    SAVE_FOR_TARGET_MIN_SCORE: number;
    ECONOMY_FARM_INCOME_TARGET_RATIO: number;
    ECONOMY_FARM_BALANCE_BONUS: number;
    ECONOMY_BASE_BALANCE_BONUS: number;
    ECONOMY_BASE_INCOME: number;
    ECONOMY_BASE_INCOME_LEVEL: number;
    ECONOMY_FARM_BUILD: number;
    ECONOMY_FARM_UPGRADE: number;
    ECONOMY_FARM_LEVEL: number;
    ECONOMY_AURA_BONUS_MULT: number;
    DEFENSE_BASE_UPGRADE: number;
    DEFENSE_WALL_BUILD: number;
    DEFENSE_WALL_UPGRADE: number;
    DEFENSE_WATCHTOWER_BUILD: number;
    DEFENSE_WATCHTOWER_UPGRADE: number;
    DEFENSE_THREAT_MULT: number;
    DEFENSE_BASE_THREAT_RADIUS: number;
    DEFENSE_BASE_THREAT_SCORE: number;
    RECONNECT_DISCONNECTED_SCORE: number;
    RECONNECT_MULTI_BONUS: number;
    RISK_ENEMY_ADJACENT_PENALTY: number;
    MAX_MOVES_PER_TURN: number;
    RANDOM_NOISE: number;
};

export type AIProfile = {
    id: string;
    label?: string;
    weights?: Partial<AIWeights>;
};

export const DefaultAIWeights: AIWeights = {
    SCORE_BASE_VALUE: AIConfig.SCORE_BASE_VALUE,
    SCORE_WIN_CONDITION: AIConfig.SCORE_WIN_CONDITION,
    SCORE_TOWN: AIConfig.SCORE_TOWN,
    SCORE_ENEMY_LAND: AIConfig.SCORE_ENEMY_LAND,
    SCORE_DISCONNECT_ENEMY: AIConfig.SCORE_DISCONNECT_ENEMY,
    SCORE_DEFEND_BASE: AIConfig.SCORE_DEFEND_BASE,
    SCORE_HILL: AIConfig.SCORE_HILL,
    SCORE_BRIDGE: AIConfig.SCORE_BRIDGE,
    SCORE_EXPANSION: AIConfig.SCORE_EXPANSION,
    SCORE_AURA_MULTIPLIER: AIConfig.SCORE_AURA_MULTIPLIER,
    COST_PENALTY_MULTIPLIER: AIConfig.COST_PENALTY_MULTIPLIER,
    SCORE_LOOKAHEAD_TOWN: AIConfig.SCORE_LOOKAHEAD_TOWN,
    SCORE_LOOKAHEAD_BASE: AIConfig.SCORE_LOOKAHEAD_BASE,
    STRATEGY_EARLY_TURN_LIMIT: AIConfig.STRATEGY_EARLY_TURN_LIMIT,
    STRATEGY_EARLY_EXPANSION_BONUS: AIConfig.STRATEGY_EARLY_EXPANSION_BONUS,
    STRATEGY_EARLY_FARM_BONUS: AIConfig.STRATEGY_EARLY_FARM_BONUS,
    STRATEGY_BASE_UPGRADE_BONUS: AIConfig.STRATEGY_BASE_UPGRADE_BONUS,
    STRATEGY_WALL_PRIORITY_BONUS: AIConfig.STRATEGY_WALL_PRIORITY_BONUS,
    STRATEGY_ENDGAME_TURN: AIConfig.STRATEGY_ENDGAME_TURN,
    STRATEGY_ENDGAME_ATTACK_BONUS: AIConfig.STRATEGY_ENDGAME_ATTACK_BONUS,
    SAVE_FOR_TARGET_MAX_TURNS: AIConfig.SAVE_FOR_TARGET_MAX_TURNS,
    SAVE_FOR_TARGET_MIN_SCORE: AIConfig.SAVE_FOR_TARGET_MIN_SCORE,
    ECONOMY_FARM_INCOME_TARGET_RATIO: AIConfig.ECONOMY_FARM_INCOME_TARGET_RATIO,
    ECONOMY_FARM_BALANCE_BONUS: AIConfig.ECONOMY_FARM_BALANCE_BONUS,
    ECONOMY_BASE_BALANCE_BONUS: AIConfig.ECONOMY_BASE_BALANCE_BONUS,
    ECONOMY_BASE_INCOME: 120,
    ECONOMY_BASE_INCOME_LEVEL: 30,
    ECONOMY_FARM_BUILD: 90,
    ECONOMY_FARM_UPGRADE: 70,
    ECONOMY_FARM_LEVEL: 25,
    ECONOMY_AURA_BONUS_MULT: 200,
    DEFENSE_BASE_UPGRADE: 120,
    DEFENSE_WALL_BUILD: 110,
    DEFENSE_WALL_UPGRADE: 90,
    DEFENSE_WATCHTOWER_BUILD: 80,
    DEFENSE_WATCHTOWER_UPGRADE: 70,
    DEFENSE_THREAT_MULT: 120,
    DEFENSE_BASE_THREAT_RADIUS: 2,
    DEFENSE_BASE_THREAT_SCORE: 600,
    RECONNECT_DISCONNECTED_SCORE: 120,
    RECONNECT_MULTI_BONUS: AIConfig.RECONNECT_MULTI_BONUS,
    RISK_ENEMY_ADJACENT_PENALTY: AIConfig.RISK_ENEMY_ADJACENT_PENALTY,
    MAX_MOVES_PER_TURN: AIConfig.MAX_MOVES_PER_TURN,
    RANDOM_NOISE: 10
};

export const EvolvedProfile1: AIProfile = {
    id: 'evolved_1768853213673_1',
    label: 'Wall Banker',
    weights: {
        COST_PENALTY_MULTIPLIER: 0.804,
        DEFENSE_BASE_THREAT_RADIUS: 3.774,
        DEFENSE_BASE_THREAT_SCORE: 349.089,
        DEFENSE_BASE_UPGRADE: 45.898,
        DEFENSE_THREAT_MULT: 56.703,
        DEFENSE_WALL_BUILD: 135.255,
        DEFENSE_WALL_UPGRADE: 411.76,
        DEFENSE_WATCHTOWER_BUILD: 65.755,
        DEFENSE_WATCHTOWER_UPGRADE: 70.836,
        ECONOMY_AURA_BONUS_MULT: 155.899,
        ECONOMY_BASE_BALANCE_BONUS: 42.772,
        ECONOMY_BASE_INCOME: 138.685,
        ECONOMY_BASE_INCOME_LEVEL: 23.094,
        ECONOMY_FARM_BALANCE_BONUS: 25.21,
        ECONOMY_FARM_BUILD: 119.898,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 0.971,
        ECONOMY_FARM_LEVEL: 65.509,
        ECONOMY_FARM_UPGRADE: 233.5,
        MAX_MOVES_PER_TURN: 41.378,
        RANDOM_NOISE: 16.088,
        RECONNECT_DISCONNECTED_SCORE: 88.999,
        RECONNECT_MULTI_BONUS: 31.981,
        RISK_ENEMY_ADJACENT_PENALTY: 52.817,
        SAVE_FOR_TARGET_MAX_TURNS: 3.248,
        SAVE_FOR_TARGET_MIN_SCORE: 452.015,
        SCORE_AURA_MULTIPLIER: 155.185,
        SCORE_BASE_VALUE: 14.353,
        SCORE_BRIDGE: 38.571,
        SCORE_DEFEND_BASE: 1791.924,
        SCORE_DISCONNECT_ENEMY: 28.373,
        SCORE_ENEMY_LAND: 141.987,
        SCORE_EXPANSION: 10.119,
        SCORE_HILL: 23.866,
        SCORE_LOOKAHEAD_BASE: 223.73,
        SCORE_LOOKAHEAD_TOWN: 71.887,
        SCORE_TOWN: 353.827,
        SCORE_WIN_CONDITION: 6564.805,
        STRATEGY_BASE_UPGRADE_BONUS: 55.615,
        STRATEGY_EARLY_EXPANSION_BONUS: 8.505,
        STRATEGY_EARLY_FARM_BONUS: 30.384,
        STRATEGY_EARLY_TURN_LIMIT: 8.191,
        STRATEGY_ENDGAME_ATTACK_BONUS: 101.431,
        STRATEGY_ENDGAME_TURN: 17.181,
        STRATEGY_WALL_PRIORITY_BONUS: 87.481,
    }
};

export const EvolvedProfile2: AIProfile = {
    id: 'evolved_1768853213673_2',
    label: 'Gold Sentinel',
    weights: {
        COST_PENALTY_MULTIPLIER: 0.869,
        DEFENSE_BASE_THREAT_RADIUS: 3.231,
        DEFENSE_BASE_THREAT_SCORE: 268.098,
        DEFENSE_BASE_UPGRADE: 44.93,
        DEFENSE_THREAT_MULT: 80.758,
        DEFENSE_WALL_BUILD: 162.473,
        DEFENSE_WALL_UPGRADE: 297.979,
        DEFENSE_WATCHTOWER_BUILD: 48.51,
        DEFENSE_WATCHTOWER_UPGRADE: 86.604,
        ECONOMY_AURA_BONUS_MULT: 160.822,
        ECONOMY_BASE_BALANCE_BONUS: 31.948,
        ECONOMY_BASE_INCOME: 299.153,
        ECONOMY_BASE_INCOME_LEVEL: 15.746,
        ECONOMY_FARM_BALANCE_BONUS: 13.408,
        ECONOMY_FARM_BUILD: 152.497,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 1.021,
        ECONOMY_FARM_LEVEL: 51.647,
        ECONOMY_FARM_UPGRADE: 234.322,
        MAX_MOVES_PER_TURN: 42.976,
        RANDOM_NOISE: 12.124,
        RECONNECT_DISCONNECTED_SCORE: 58.087,
        RECONNECT_MULTI_BONUS: 35.923,
        RISK_ENEMY_ADJACENT_PENALTY: 75.599,
        SAVE_FOR_TARGET_MAX_TURNS: 3.52,
        SAVE_FOR_TARGET_MIN_SCORE: 619.512,
        SCORE_AURA_MULTIPLIER: 111.575,
        SCORE_BASE_VALUE: 8.43,
        SCORE_BRIDGE: 21.374,
        SCORE_DEFEND_BASE: 1979.606,
        SCORE_DISCONNECT_ENEMY: 36.617,
        SCORE_ENEMY_LAND: 110.009,
        SCORE_EXPANSION: 8.557,
        SCORE_HILL: 33.14,
        SCORE_LOOKAHEAD_BASE: 321.314,
        SCORE_LOOKAHEAD_TOWN: 98.176,
        SCORE_TOWN: 453.48,
        SCORE_WIN_CONDITION: 10583.199,
        STRATEGY_BASE_UPGRADE_BONUS: 36.115,
        STRATEGY_EARLY_EXPANSION_BONUS: 7.874,
        STRATEGY_EARLY_FARM_BONUS: 24.906,
        STRATEGY_EARLY_TURN_LIMIT: 3.644,
        STRATEGY_ENDGAME_ATTACK_BONUS: 64.223,
        STRATEGY_ENDGAME_TURN: 13.207,
        STRATEGY_WALL_PRIORITY_BONUS: 55.674,
    }
};

export const EvolvedProfile3: AIProfile = {
    id: 'evolved_1768853213673_3',
    label: 'Strategic Surge',
    weights: {
        COST_PENALTY_MULTIPLIER: 0.676,
        DEFENSE_BASE_THREAT_RADIUS: 3.093,
        DEFENSE_BASE_THREAT_SCORE: 451.82,
        DEFENSE_BASE_UPGRADE: 62.066,
        DEFENSE_THREAT_MULT: 106.638,
        DEFENSE_WALL_BUILD: 67.59,
        DEFENSE_WALL_UPGRADE: 229.658,
        DEFENSE_WATCHTOWER_BUILD: 17.055,
        DEFENSE_WATCHTOWER_UPGRADE: 78.93,
        ECONOMY_AURA_BONUS_MULT: 199.686,
        ECONOMY_BASE_BALANCE_BONUS: 34.091,
        ECONOMY_BASE_INCOME: 233.729,
        ECONOMY_BASE_INCOME_LEVEL: 20.437,
        ECONOMY_FARM_BALANCE_BONUS: 14.159,
        ECONOMY_FARM_BUILD: 100.688,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 0.315,
        ECONOMY_FARM_LEVEL: 35.733,
        ECONOMY_FARM_UPGRADE: 177.11,
        MAX_MOVES_PER_TURN: 46.277,
        RANDOM_NOISE: 5.877,
        RECONNECT_DISCONNECTED_SCORE: 100.127,
        RECONNECT_MULTI_BONUS: 52.826,
        RISK_ENEMY_ADJACENT_PENALTY: 71.356,
        SAVE_FOR_TARGET_MAX_TURNS: 2.38,
        SAVE_FOR_TARGET_MIN_SCORE: 324.921,
        SCORE_AURA_MULTIPLIER: 129.544,
        SCORE_BASE_VALUE: 11.052,
        SCORE_BRIDGE: 27.63,
        SCORE_DEFEND_BASE: 3051.561,
        SCORE_DISCONNECT_ENEMY: 39.69,
        SCORE_ENEMY_LAND: 115.27,
        SCORE_EXPANSION: 9.497,
        SCORE_HILL: 41.88,
        SCORE_LOOKAHEAD_BASE: 253.156,
        SCORE_LOOKAHEAD_TOWN: 161.456,
        SCORE_TOWN: 415.218,
        SCORE_WIN_CONDITION: 9384.407,
        STRATEGY_BASE_UPGRADE_BONUS: 44.657,
        STRATEGY_EARLY_EXPANSION_BONUS: 7.186,
        STRATEGY_EARLY_FARM_BONUS: 41.242,
        STRATEGY_EARLY_TURN_LIMIT: 8.003,
        STRATEGY_ENDGAME_ATTACK_BONUS: 91.76,
        STRATEGY_ENDGAME_TURN: 12.588,
        STRATEGY_WALL_PRIORITY_BONUS: 82.178,
    }
};

export const EvolvedProfile4: AIProfile = {
    id: 'evolved_1768853213673_4',
    label: 'Iron Economist',
    weights: {
        COST_PENALTY_MULTIPLIER: 0.626,
        DEFENSE_BASE_THREAT_RADIUS: 2.815,
        DEFENSE_BASE_THREAT_SCORE: 338.237,
        DEFENSE_BASE_UPGRADE: 53.137,
        DEFENSE_THREAT_MULT: 86.842,
        DEFENSE_WALL_BUILD: 120.863,
        DEFENSE_WALL_UPGRADE: 375.051,
        DEFENSE_WATCHTOWER_BUILD: 50.602,
        DEFENSE_WATCHTOWER_UPGRADE: 63.757,
        ECONOMY_AURA_BONUS_MULT: 135.235,
        ECONOMY_BASE_BALANCE_BONUS: 50.931,
        ECONOMY_BASE_INCOME: 222.375,
        ECONOMY_BASE_INCOME_LEVEL: 25.323,
        ECONOMY_FARM_BALANCE_BONUS: 19.97,
        ECONOMY_FARM_BUILD: 112.511,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 0.867,
        ECONOMY_FARM_LEVEL: 51.295,
        ECONOMY_FARM_UPGRADE: 190.882,
        MAX_MOVES_PER_TURN: 51.538,
        RANDOM_NOISE: 12.16,
        RECONNECT_DISCONNECTED_SCORE: 73.695,
        RECONNECT_MULTI_BONUS: 50.503,
        RISK_ENEMY_ADJACENT_PENALTY: 83.473,
        SAVE_FOR_TARGET_MAX_TURNS: 3.017,
        SAVE_FOR_TARGET_MIN_SCORE: 535.268,
        SCORE_AURA_MULTIPLIER: 151.912,
        SCORE_BASE_VALUE: 13.165,
        SCORE_BRIDGE: 29.338,
        SCORE_DEFEND_BASE: 1596.891,
        SCORE_DISCONNECT_ENEMY: 43.893,
        SCORE_ENEMY_LAND: 148.452,
        SCORE_EXPANSION: 9.791,
        SCORE_HILL: 37.451,
        SCORE_LOOKAHEAD_BASE: 251.823,
        SCORE_LOOKAHEAD_TOWN: 117.266,
        SCORE_TOWN: 484.145,
        SCORE_WIN_CONDITION: 9602.605,
        STRATEGY_BASE_UPGRADE_BONUS: 47.328,
        STRATEGY_EARLY_EXPANSION_BONUS: 11.778,
        STRATEGY_EARLY_FARM_BONUS: 37.886,
        STRATEGY_EARLY_TURN_LIMIT: 5.94,
        STRATEGY_ENDGAME_ATTACK_BONUS: 99.694,
        STRATEGY_ENDGAME_TURN: 16.228,
        STRATEGY_WALL_PRIORITY_BONUS: 64.882,
    }
};

export const RandomAiProfiles: AIProfile[] = [
    EvolvedProfile1,
    EvolvedProfile2,
    EvolvedProfile3,
    EvolvedProfile4
];

export const DefaultAIProfile: AIProfile = EvolvedProfile1;

export const mergeAIWeights = (overrides?: Partial<AIWeights>): AIWeights => {
    return {
        ...DefaultAIWeights,
        ...(overrides || {})
    };
};
