import { AIConfig } from '../AIConfig';

export type AIWeights = {
    SCORE_BASE_VALUE: number;
    SCORE_WIN_CONDITION: number;
    SCORE_TOWN: number;
    SCORE_ENEMY_LAND: number;
    SCORE_DISCONNECT_ENEMY: number;
    SCORE_DEFEND_BASE: number;
    SCORE_HILL: number;
    SCORE_BRIDGE: number;
    SCORE_EXPANSION: number;
    SCORE_AURA_MULTIPLIER: number;
    COST_PENALTY_MULTIPLIER: number;
    SCORE_LOOKAHEAD_TOWN: number;
    SCORE_LOOKAHEAD_BASE: number;
    STRATEGY_EARLY_TURN_LIMIT: number;
    STRATEGY_EARLY_EXPANSION_BONUS: number;
    STRATEGY_EARLY_FARM_BONUS: number;
    STRATEGY_BASE_UPGRADE_BONUS: number;
    STRATEGY_WALL_PRIORITY_BONUS: number;
    STRATEGY_ENDGAME_TURN: number;
    STRATEGY_ENDGAME_ATTACK_BONUS: number;
    SAVE_FOR_TARGET_MAX_TURNS: number;
    SAVE_FOR_TARGET_MIN_SCORE: number;
    ECONOMY_FARM_INCOME_TARGET_RATIO: number;
    ECONOMY_FARM_BALANCE_BONUS: number;
    ECONOMY_BASE_BALANCE_BONUS: number;
    ECONOMY_BASE_INCOME: number;
    ECONOMY_BASE_INCOME_LEVEL: number;
    ECONOMY_FARM_BUILD: number;
    ECONOMY_FARM_UPGRADE: number;
    ECONOMY_FARM_LEVEL: number;
    ECONOMY_AURA_BONUS_MULT: number;
    DEFENSE_BASE_UPGRADE: number;
    DEFENSE_WALL_BUILD: number;
    DEFENSE_WALL_UPGRADE: number;
    DEFENSE_WATCHTOWER_BUILD: number;
    DEFENSE_WATCHTOWER_UPGRADE: number;
    DEFENSE_THREAT_MULT: number;
    DEFENSE_BASE_THREAT_RADIUS: number;
    DEFENSE_BASE_THREAT_SCORE: number;
    RECONNECT_DISCONNECTED_SCORE: number;
    RECONNECT_MULTI_BONUS: number;
    RISK_ENEMY_ADJACENT_PENALTY: number;
    MAX_MOVES_PER_TURN: number;
    RANDOM_NOISE: number;
};

export type AIProfile = {
    id: string;
    label?: string;
    weights?: Partial<AIWeights>;
};

export const DefaultAIWeights: AIWeights = {
    SCORE_BASE_VALUE: AIConfig.SCORE_BASE_VALUE,
    SCORE_WIN_CONDITION: AIConfig.SCORE_WIN_CONDITION,
    SCORE_TOWN: AIConfig.SCORE_TOWN,
    SCORE_ENEMY_LAND: AIConfig.SCORE_ENEMY_LAND,
    SCORE_DISCONNECT_ENEMY: AIConfig.SCORE_DISCONNECT_ENEMY,
    SCORE_DEFEND_BASE: AIConfig.SCORE_DEFEND_BASE,
    SCORE_HILL: AIConfig.SCORE_HILL,
    SCORE_BRIDGE: AIConfig.SCORE_BRIDGE,
    SCORE_EXPANSION: AIConfig.SCORE_EXPANSION,
    SCORE_AURA_MULTIPLIER: AIConfig.SCORE_AURA_MULTIPLIER,
    COST_PENALTY_MULTIPLIER: AIConfig.COST_PENALTY_MULTIPLIER,
    SCORE_LOOKAHEAD_TOWN: AIConfig.SCORE_LOOKAHEAD_TOWN,
    SCORE_LOOKAHEAD_BASE: AIConfig.SCORE_LOOKAHEAD_BASE,
    STRATEGY_EARLY_TURN_LIMIT: AIConfig.STRATEGY_EARLY_TURN_LIMIT,
    STRATEGY_EARLY_EXPANSION_BONUS: AIConfig.STRATEGY_EARLY_EXPANSION_BONUS,
    STRATEGY_EARLY_FARM_BONUS: AIConfig.STRATEGY_EARLY_FARM_BONUS,
    STRATEGY_BASE_UPGRADE_BONUS: AIConfig.STRATEGY_BASE_UPGRADE_BONUS,
    STRATEGY_WALL_PRIORITY_BONUS: AIConfig.STRATEGY_WALL_PRIORITY_BONUS,
    STRATEGY_ENDGAME_TURN: AIConfig.STRATEGY_ENDGAME_TURN,
    STRATEGY_ENDGAME_ATTACK_BONUS: AIConfig.STRATEGY_ENDGAME_ATTACK_BONUS,
    SAVE_FOR_TARGET_MAX_TURNS: AIConfig.SAVE_FOR_TARGET_MAX_TURNS,
    SAVE_FOR_TARGET_MIN_SCORE: AIConfig.SAVE_FOR_TARGET_MIN_SCORE,
    ECONOMY_FARM_INCOME_TARGET_RATIO: AIConfig.ECONOMY_FARM_INCOME_TARGET_RATIO,
    ECONOMY_FARM_BALANCE_BONUS: AIConfig.ECONOMY_FARM_BALANCE_BONUS,
    ECONOMY_BASE_BALANCE_BONUS: AIConfig.ECONOMY_BASE_BALANCE_BONUS,
    ECONOMY_BASE_INCOME: AIConfig.ECONOMY_BASE_INCOME,
    ECONOMY_BASE_INCOME_LEVEL: AIConfig.ECONOMY_BASE_INCOME_LEVEL,
    ECONOMY_FARM_BUILD: AIConfig.ECONOMY_FARM_BUILD,
    ECONOMY_FARM_UPGRADE: AIConfig.ECONOMY_FARM_UPGRADE,
    ECONOMY_FARM_LEVEL: AIConfig.ECONOMY_FARM_LEVEL,
    ECONOMY_AURA_BONUS_MULT: AIConfig.ECONOMY_AURA_BONUS_MULT,
    DEFENSE_BASE_UPGRADE: AIConfig.DEFENSE_BASE_UPGRADE,
    DEFENSE_WALL_BUILD: AIConfig.DEFENSE_WALL_BUILD,
    DEFENSE_WALL_UPGRADE: AIConfig.DEFENSE_WALL_UPGRADE,
    DEFENSE_WATCHTOWER_BUILD: AIConfig.DEFENSE_WATCHTOWER_BUILD,
    DEFENSE_WATCHTOWER_UPGRADE: AIConfig.DEFENSE_WATCHTOWER_UPGRADE,
    DEFENSE_THREAT_MULT: AIConfig.DEFENSE_THREAT_MULT,
    DEFENSE_BASE_THREAT_RADIUS: AIConfig.DEFENSE_BASE_THREAT_RADIUS,
    DEFENSE_BASE_THREAT_SCORE: AIConfig.DEFENSE_BASE_THREAT_SCORE,
    RECONNECT_DISCONNECTED_SCORE: AIConfig.RECONNECT_DISCONNECTED_SCORE,
    RECONNECT_MULTI_BONUS: AIConfig.RECONNECT_MULTI_BONUS,
    RISK_ENEMY_ADJACENT_PENALTY: AIConfig.RISK_ENEMY_ADJACENT_PENALTY,
    MAX_MOVES_PER_TURN: AIConfig.MAX_MOVES_PER_TURN,
    RANDOM_NOISE: AIConfig.RANDOM_NOISE
};

export const EvolvedProfile1: AIProfile = {
    id: 'evolved_1768887753358_1',
    label: 'Leader Quinn',
    weights: {
        COST_PENALTY_MULTIPLIER: 1.176,
        DEFENSE_BASE_THREAT_RADIUS: 2.22,
        DEFENSE_BASE_THREAT_SCORE: 187.285,
        DEFENSE_BASE_UPGRADE: 37.958,
        DEFENSE_THREAT_MULT: 41.155,
        DEFENSE_WALL_BUILD: 97.653,
        DEFENSE_WALL_UPGRADE: 305.086,
        DEFENSE_WATCHTOWER_BUILD: 19.023,
        DEFENSE_WATCHTOWER_UPGRADE: 76.712,
        ECONOMY_AURA_BONUS_MULT: 105.687,
        ECONOMY_BASE_BALANCE_BONUS: 21.198,
        ECONOMY_BASE_INCOME: 179.701,
        ECONOMY_BASE_INCOME_LEVEL: 27.953,
        ECONOMY_FARM_BALANCE_BONUS: 22.237,
        ECONOMY_FARM_BUILD: 108.619,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 0.943,
        ECONOMY_FARM_LEVEL: 49.903,
        ECONOMY_FARM_UPGRADE: 245.741,
        MAX_MOVES_PER_TURN: 29.75,
        RANDOM_NOISE: 20.813,
        RECONNECT_DISCONNECTED_SCORE: 44.916,
        RECONNECT_MULTI_BONUS: 27.495,
        RISK_ENEMY_ADJACENT_PENALTY: 144.343,
        SAVE_FOR_TARGET_MAX_TURNS: 3.645,
        SAVE_FOR_TARGET_MIN_SCORE: 319.068,
        SCORE_AURA_MULTIPLIER: 288.801,
        SCORE_BASE_VALUE: 11.326,
        SCORE_BRIDGE: 24.616,
        SCORE_DEFEND_BASE: 952.955,
        SCORE_DISCONNECT_ENEMY: 44.35,
        SCORE_ENEMY_LAND: 37.999,
        SCORE_EXPANSION: 11.978,
        SCORE_HILL: 37.681,
        SCORE_LOOKAHEAD_BASE: 304.184,
        SCORE_LOOKAHEAD_TOWN: 61.785,
        SCORE_TOWN: 165.131,
        SCORE_WIN_CONDITION: 5209.291,
        STRATEGY_BASE_UPGRADE_BONUS: 26.72,
        STRATEGY_EARLY_EXPANSION_BONUS: 10.248,
        STRATEGY_EARLY_FARM_BONUS: 33.941,
        STRATEGY_EARLY_TURN_LIMIT: 4.547,
        STRATEGY_ENDGAME_ATTACK_BONUS: 61.469,
        STRATEGY_ENDGAME_TURN: 7.501,
        STRATEGY_WALL_PRIORITY_BONUS: 65.946,
    }
};

export const EvolvedProfile2: AIProfile = {
    id: 'evolved_1768887753358_2',
    label: 'Leader Rose',
    weights: {
        COST_PENALTY_MULTIPLIER: 1.17,
        DEFENSE_BASE_THREAT_RADIUS: 2.133,
        DEFENSE_BASE_THREAT_SCORE: 174.06,
        DEFENSE_BASE_UPGRADE: 39.543,
        DEFENSE_THREAT_MULT: 40.26,
        DEFENSE_WALL_BUILD: 87.36,
        DEFENSE_WALL_UPGRADE: 301.052,
        DEFENSE_WATCHTOWER_BUILD: 19.023,
        DEFENSE_WATCHTOWER_UPGRADE: 80.942,
        ECONOMY_AURA_BONUS_MULT: 105.408,
        ECONOMY_BASE_BALANCE_BONUS: 21.068,
        ECONOMY_BASE_INCOME: 171.873,
        ECONOMY_BASE_INCOME_LEVEL: 26.768,
        ECONOMY_FARM_BALANCE_BONUS: 21.95,
        ECONOMY_FARM_BUILD: 105.918,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 0.988,
        ECONOMY_FARM_LEVEL: 52.147,
        ECONOMY_FARM_UPGRADE: 228.052,
        MAX_MOVES_PER_TURN: 30.623,
        RANDOM_NOISE: 21.82,
        RECONNECT_DISCONNECTED_SCORE: 45.098,
        RECONNECT_MULTI_BONUS: 28.427,
        RISK_ENEMY_ADJACENT_PENALTY: 132.133,
        SAVE_FOR_TARGET_MAX_TURNS: 3.506,
        SAVE_FOR_TARGET_MIN_SCORE: 317.032,
        SCORE_AURA_MULTIPLIER: 281.6,
        SCORE_BASE_VALUE: 11.57,
        SCORE_BRIDGE: 23.482,
        SCORE_DEFEND_BASE: 970.006,
        SCORE_DISCONNECT_ENEMY: 50.404,
        SCORE_ENEMY_LAND: 40.803,
        SCORE_EXPANSION: 11.754,
        SCORE_HILL: 38.804,
        SCORE_LOOKAHEAD_BASE: 308.175,
        SCORE_LOOKAHEAD_TOWN: 58.263,
        SCORE_TOWN: 162.069,
        SCORE_WIN_CONDITION: 4751.893,
        STRATEGY_BASE_UPGRADE_BONUS: 26.324,
        STRATEGY_EARLY_EXPANSION_BONUS: 9.533,
        STRATEGY_EARLY_FARM_BONUS: 37.975,
        STRATEGY_EARLY_TURN_LIMIT: 4.88,
        STRATEGY_ENDGAME_ATTACK_BONUS: 61.773,
        STRATEGY_ENDGAME_TURN: 8.125,
        STRATEGY_WALL_PRIORITY_BONUS: 69.36,
    }
};

export const EvolvedProfile3: AIProfile = {
    id: 'evolved_1768887753358_3',
    label: 'Leader Sam',
    weights: {
        COST_PENALTY_MULTIPLIER: 1.169,
        DEFENSE_BASE_THREAT_RADIUS: 2.046,
        DEFENSE_BASE_THREAT_SCORE: 192.914,
        DEFENSE_BASE_UPGRADE: 37.763,
        DEFENSE_THREAT_MULT: 42.81,
        DEFENSE_WALL_BUILD: 106.312,
        DEFENSE_WALL_UPGRADE: 288.379,
        DEFENSE_WATCHTOWER_BUILD: 15.553,
        DEFENSE_WATCHTOWER_UPGRADE: 67.895,
        ECONOMY_AURA_BONUS_MULT: 107.907,
        ECONOMY_BASE_BALANCE_BONUS: 18.592,
        ECONOMY_BASE_INCOME: 187.442,
        ECONOMY_BASE_INCOME_LEVEL: 25.913,
        ECONOMY_FARM_BALANCE_BONUS: 21.89,
        ECONOMY_FARM_BUILD: 115.022,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 1.083,
        ECONOMY_FARM_LEVEL: 57.628,
        ECONOMY_FARM_UPGRADE: 254.321,
        MAX_MOVES_PER_TURN: 31.424,
        RANDOM_NOISE: 20.103,
        RECONNECT_DISCONNECTED_SCORE: 47.116,
        RECONNECT_MULTI_BONUS: 25.162,
        RISK_ENEMY_ADJACENT_PENALTY: 142.269,
        SAVE_FOR_TARGET_MAX_TURNS: 3.461,
        SAVE_FOR_TARGET_MIN_SCORE: 345.873,
        SCORE_AURA_MULTIPLIER: 322.633,
        SCORE_BASE_VALUE: 11.463,
        SCORE_BRIDGE: 25.333,
        SCORE_DEFEND_BASE: 970.76,
        SCORE_DISCONNECT_ENEMY: 45.261,
        SCORE_ENEMY_LAND: 41.309,
        SCORE_EXPANSION: 12.538,
        SCORE_HILL: 35.889,
        SCORE_LOOKAHEAD_BASE: 288.247,
        SCORE_LOOKAHEAD_TOWN: 62.952,
        SCORE_TOWN: 153.586,
        SCORE_WIN_CONDITION: 4704.435,
        STRATEGY_BASE_UPGRADE_BONUS: 23.979,
        STRATEGY_EARLY_EXPANSION_BONUS: 9.723,
        STRATEGY_EARLY_FARM_BONUS: 35.507,
        STRATEGY_EARLY_TURN_LIMIT: 3.933,
        STRATEGY_ENDGAME_ATTACK_BONUS: 68.258,
        STRATEGY_ENDGAME_TURN: 8.067,
        STRATEGY_WALL_PRIORITY_BONUS: 53.387,
    }
};

export const EvolvedProfile4: AIProfile = {
    id: 'evolved_1768887753358_4',
    label: 'Leader Tina',
    weights: {
        COST_PENALTY_MULTIPLIER: 1.23,
        DEFENSE_BASE_THREAT_RADIUS: 1.927,
        DEFENSE_BASE_THREAT_SCORE: 197.117,
        DEFENSE_BASE_UPGRADE: 38.968,
        DEFENSE_THREAT_MULT: 45.101,
        DEFENSE_WALL_BUILD: 99.68,
        DEFENSE_WALL_UPGRADE: 278.572,
        DEFENSE_WATCHTOWER_BUILD: 14.619,
        DEFENSE_WATCHTOWER_UPGRADE: 64.324,
        ECONOMY_AURA_BONUS_MULT: 110.434,
        ECONOMY_BASE_BALANCE_BONUS: 19.272,
        ECONOMY_BASE_INCOME: 187.853,
        ECONOMY_BASE_INCOME_LEVEL: 26.734,
        ECONOMY_FARM_BALANCE_BONUS: 23.015,
        ECONOMY_FARM_BUILD: 108.854,
        ECONOMY_FARM_INCOME_TARGET_RATIO: 1.142,
        ECONOMY_FARM_LEVEL: 60.094,
        ECONOMY_FARM_UPGRADE: 257.905,
        MAX_MOVES_PER_TURN: 32.346,
        RANDOM_NOISE: 20.615,
        RECONNECT_DISCONNECTED_SCORE: 47.731,
        RECONNECT_MULTI_BONUS: 25.419,
        RISK_ENEMY_ADJACENT_PENALTY: 150.247,
        SAVE_FOR_TARGET_MAX_TURNS: 3.431,
        SAVE_FOR_TARGET_MIN_SCORE: 350.261,
        SCORE_AURA_MULTIPLIER: 313.182,
        SCORE_BASE_VALUE: 11.864,
        SCORE_BRIDGE: 26.386,
        SCORE_DEFEND_BASE: 918.507,
        SCORE_DISCONNECT_ENEMY: 42.459,
        SCORE_ENEMY_LAND: 40.367,
        SCORE_EXPANSION: 12.823,
        SCORE_HILL: 35.559,
        SCORE_LOOKAHEAD_BASE: 302.626,
        SCORE_LOOKAHEAD_TOWN: 65.684,
        SCORE_TOWN: 143.324,
        SCORE_WIN_CONDITION: 4786.843,
        STRATEGY_BASE_UPGRADE_BONUS: 23.413,
        STRATEGY_EARLY_EXPANSION_BONUS: 9.975,
        STRATEGY_EARLY_FARM_BONUS: 37.432,
        STRATEGY_EARLY_TURN_LIMIT: 3.924,
        STRATEGY_ENDGAME_ATTACK_BONUS: 67.639,
        STRATEGY_ENDGAME_TURN: 8.555,
        STRATEGY_WALL_PRIORITY_BONUS: 52.591,
    }
};

export const RandomAiProfiles: AIProfile[] = [
    EvolvedProfile1,
    EvolvedProfile2,
    EvolvedProfile3,
    EvolvedProfile4
];

export const DefaultAIProfile: AIProfile = EvolvedProfile1;

export const mergeAIWeights = (overrides?: Partial<AIWeights>): AIWeights => {
    return {
        ...DefaultAIWeights,
        ...(overrides || {})
    };
};
