export const AIConfig = {
    // Objectives
    SCORE_BASE_VALUE: 10,
    SCORE_WIN_CONDITION: 10000,
    SCORE_TOWN: 500,

    // Aggression
    SCORE_ENEMY_LAND: 100,
    SCORE_DISCONNECT_ENEMY: 50,
    SCORE_DEFEND_BASE: 2000,

    // Terrain
    SCORE_HILL: 50,
    SCORE_BRIDGE: 60,

    // Expansion
    SCORE_EXPANSION: 20,

    // Modifiers
    SCORE_AURA_MULTIPLIER: 200,
    COST_PENALTY_MULTIPLIER: 0.5,

    // Look-Ahead
    SCORE_LOOKAHEAD_TOWN: 100,
    SCORE_LOOKAHEAD_BASE: 200,

    // Strategy Phases
    STRATEGY_EARLY_TURN_LIMIT: 5,
    STRATEGY_EARLY_EXPANSION_BONUS: 40,
    STRATEGY_EARLY_FARM_BONUS: 60,
    STRATEGY_BASE_UPGRADE_BONUS: 80,
    STRATEGY_WALL_PRIORITY_BONUS: 90,
    STRATEGY_ENDGAME_TURN: 20,
    STRATEGY_ENDGAME_ATTACK_BONUS: 120,

    // Savings for high-value targets
    SAVE_FOR_TARGET_MAX_TURNS: 2,
    SAVE_FOR_TARGET_MIN_SCORE: 1000,

    // Economy balance
    ECONOMY_FARM_INCOME_TARGET_RATIO: 0.8,
    ECONOMY_FARM_BALANCE_BONUS: 50,
    ECONOMY_BASE_BALANCE_BONUS: 50,

    // Risk / connectivity
    RISK_ENEMY_ADJACENT_PENALTY: 40,
    RECONNECT_MULTI_BONUS: 60,

    // Limits
    MAX_MOVES_PER_TURN: 50
};
